### ISSUE TITLE
o jee, ik kan het nog steeds niet ;-( Respec is stuk

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/PCB#1]
@redmer zou jij me kunnen helpen? Het PCB gaat ReSpec maar met zomaar een voorbeeld kopiëren lukt het me niet fantastisch, wil jij helpen en zorgen dat het beheerplan het doet?

**Comment by redmer** [comment]
Closed in https://github.com/Stichting-CROW/PCB/commit/3ec1dd3152292e20b73f8891740db379eb3ea22f

**Comment by redmer** [comment]
Het bleek een komma, verwerkt in https://github.com/Stichting-CROW/PCB/commit/3ec1dd3152292e20b73f8891740db379eb3ea22f
