### ISSUE TITLE
Feedback Informatiemodel Contractspecificaties: Eistypen

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/PCB#39]
**Betreft onderdeel**:  (zo expliciet mogelijk zoals pagina, alinea, eisnummer, stap, etc.)
**Verbetervoorstel**: Een standaard lijst met Eistypen afspreken bij Provincies, voor beter opdrachtgeverschap naar opdrachtnemers en makkelijker werken in Relatics omgevingen bij het inlezen van de colectieve eisen.
**Beoogd doel van de verbetering**: (‘als we dit niet doen, dan…’, ‘hierdoor kunnen we…’, etc.)

**Comment by ElisabethKloren** [comment]
Bij BIM loket laatste stand van zaken, daar kwam helaas geen consensus uit:

De aspecteisen zijn grotendeels overgenomen uit de [[LeidraadSE3]]; de eistypen die aanduiden aan wat voor concept de eis is gesteld zijn aangepast aan de onderwerpen uit deze richtlijn. Dit is een enumeratie.

Bij uitwisseling mag je uitsluitend de onderstaande lijst gebruiken, zonder zelf uitbreidingen te doen. Als elke opdrachtgever een eigen lijst met eistypen en aspecten gebruikt wordt het inrichten van standaard omgevingen voor de verwerking van contracteisen onnodig bemoeilijkt, waarbij bij elk project een aangepaste lijst moet worden gemaakt.

Eistypen:


<dl>
<dt><dfn>Informatie-eis
   <dd>Eis gesteld aan een te leveren [=Informatieproduct=]
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Informatie-eis">csw:Informatie-eis</a>
	   
<dt><dfn>Systeemeis
   <dd>Eis gesteld aan een [=FysiekObject=]
   <dd>Een eis die het tot stand komen en gebruiken dan wel toepassen van het geïntegreerde systeem specificeert. Bron: [[LeidraadSE3]]
   <dd>Andere in de sector gebruikte namen van eisen die allemaal tot de Systeemeisen behoren: Functionele eis; Prestatie-eis; Technische eis; Ontwerprandvoorwaarde
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Systeemeis">csw:Systeemeis</a>
	 
<dt><dfn>Proceseis
   <dd>Eis gesteld aan een [=Werkzaamheid=]
   <dd>De beschrijving van het gevraagde geheel van samenhangende of elkaar beïnvloedende activiteiten dat input omzet in output. Bron: [[LeidraadSE3]] 
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Proceseis">csw:Proceseis</a>

<dt><dfn>Functie-eis
   <dd>Eis gesteld aan een [=Functie=]
   <dd>De beschrijving van de gevraagde beoogde werking en/of verrichting van een systeem. Bron: [[LeidraadSE3]]
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Functie-eis">csw:Functie-eis</a>

<dt><dfn>Aspecteis: Betrouwbaarheid
   <dd>De waarschijnlijkheid dat de vereiste functie wordt uitgevoerd onder gegeven omstandigheden gedurende een bepaald tijdsinterval. 
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Aspecteis-Betrouwbaarheid">csw:Aspecteis-Betrouwbaarheid</a>
 <dd>Bron: [[LeidraadSE3]]

<dt><dfn>Aspecteis: Beschikbaarheid
   <dd>De waarschijnlijkheid dat de vereiste functie op een willekeurig moment kan worden uitgevoerd onder gegeven omstandigheden.	
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Aspecteis-Beschikbaarheid">csw:Aspecteis-Beschikbaarheid</a>
 <dd>Bron: [[LeidraadSE3]]

<dt><dfn>Aspecteis: Onderhoudbaarheid
   <dd>De waarschijnlijkheid dat de activiteiten voor onderhoud kunnen worden uitgevoerd binnen de hiervoor vastgestelde tijden, onder gegeven omstandigheden teneinde de vereiste functie te kunnen (blijven) uitvoeren.
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Aspecteis-Onderhoudbaarheid">csw:Aspecteis-Onderhoudbaarheid</a>
 <dd>Bron: [[LeidraadSE3]]

<dt><dfn>Aspecteis: Veiligheid
   <dd>De waarschijnlijkheid dat de vereiste functie en de daarvoor benodigde activiteiten zonder optredend letsel aan personen kan worden vervuld dan wel uitgevoerd en de waarschijnlijkheid dat de integriteit van de functie  en de daaraan verbonden data en datastructuren gewaarborgd blijven van ongewenste beïnvloeding.	   
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Aspecteis-Veiligheid">csw:Aspecteis-Veiligheid</a>
 <dd>Bron: [[LeidraadSE3]]

<dt><dfn>Aspecteis: Gezondheid
   <dd>De waarschijnlijkheid dat de vereiste functie en de daarvoor benodigde activiteiten zonder negatieve gezondheidsrisico's voor personen kan worden vervuld dan wel uitgevoerd.
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Aspecteis-Gezondheid">csw:Aspecteis-Gezondheid</a>
   <dd>Bron: [[LeidraadSE3]]

<dt><dfn>Aspecteis: Omgeving
   <dd>De waarschijnlijkheid dat de vereiste functie en de daarvoor benodigde activiteiten zonder ongewenste risico's voor de omgeving kunnen wordenvervuld en/of gerealiseerd.	
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Aspecteis-Omgeving">csw:Aspecteis-Omgeving</a>    
   <dd>Bron: [[LeidraadSE3]]

<dt><dfn>Aspecteis: Duurzaamheid
   <dd>De waarschijnlijkheid dat de vereiste functie en de daarvoor benodigde activiteiten binnen de hieraan gestelde eisen en PPP (People/Planet/Profit)-doelstellingen kunnen worden gerealiseerd.  
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Aspecteis-Duurzaamheid">csw:Aspecteis-Duurzaamheid</a>
   <dd>Bron: [[LeidraadSE3]]

<dt><dfn>Aspecteis: Vormgeving
   <dd>De beschrijving van de gevraagde prestatie ten aanzien van het beeld en het materiaalgebruik met inachtneming van de omgevings- en de gezondheidseisen van het systeem en haar onderdelen.
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Aspecteis-Vormgeving">csw:Aspecteis-Vormgeving</a>
   <dd>Bron: Leidraad SE v3

<dt><dfn>Aspecteis: Toekomstvastheid
   <dd>De beschrijving van de gevraagde prestatie van een systeem ten aanzien van de vereiste levensduur van het systeem (als functie en als object) en haar onderdelen.	    
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Aspecteis-Toekomstvastheid">csw:Aspecteis-Toekomstvastheid</a>
   <dd>Bron: [[LeidraadSE3]]

<dt><dfn>Aspecteis: Sloopbaarheid
   <dd>De waarschijnlijkheid dat de vereiste functie aan het einde van de levensduur op beheerste wijze kan worden teruggebracht tot minimaal secundaire grondstoffen en met inachtneming van de overige aspecten.  
   <dd><a href="https://data.crow.nl/contractspecificaties/id/Aspecteis-Sloopbaarheid">csw:Aspecteis-Sloopbaarheid</a>
   <dd>Bron: [[LeidraadSE3]]
</dd></dl>

**Comment by ElisabethKloren** [comment]
Zie ook het reviewcommentaar HIER: https://github.com/bimloket/contractspecificaties/issues/48

**Comment by BobNonnekens** [comment]
Bij het Provinciaal Contractenbuffet en ProContract schreven we in september 2021 al het volgende:

[eisenindeling.pdf](https://github.com/Stichting-CROW/PCB/files/10344379/eisenindeling.pdf)

**Comment by BobNonnekens** [comment]
Vervolgens hebben we in de eerste helft van 2022 in aansluiting op de actualisatie van de NEN 2660-1&2: 2022 NL intern CROW in samenwerking met onder andere jou de eisstructuur volledig over de PCB-producten geharmoniseerd en NEN-proof gemaakt. Hiermee was op dat moment ook de aansluiting met BIM geregeld. In hoeverre is het bovenstaand aangerdragen voorstel op deze ontwikkeling van afgelopen jaar afgestemd? Ik zie nu nieuwe definities voor dezelfde Lemma's ontstaan. Dat is ongewenst. De SE-Leidraad is geen geharmoniseerde norm en daardoor minder gewenst als bron, daar waar de NEN-proof PCB uitwerking dat voor vrijwel alle Lemma's wel is.

**Comment by ElisabethKloren** [comment]
> Vervolgens hebben we in de eerste helft van 2022 in aansluiting op de actualisatie van de NEN 2660-1&2: 2022 NL intern CROW in samenwerking met onder andere jou de eisstructuur volledig over de PCB-producten geharmoniseerd en NEN-proof gemaakt. Hiermee was op dat moment ook de aansluiting met BIM geregeld. In hoeverre is het bovenstaand aangerdragen voorstel op deze ontwikkeling van afgelopen jaar afgestemd? Ik zie nu nieuwe definities voor dezelfde Lemma's ontstaan. Dat is ongewenst. De SE-Leidraad is geen geharmoniseerde norm en daardoor minder gewenst als bron, daar waar de NEN-proof PCB uitwerking dat voor vrijwel alle Lemma's wel is.

Hoi @BobNonnekens er is dus géen overeenstemming gekomen op de eistypen, wel is het zo dat het voorstel nog is gewijzigd. We zullen bij het PCB zelf onze eistypen moeten definiëren. Bovenstaand was de wijsheid van velen; ik stel voor dat het kernteam een lijst vaststelt op basis van bovenstaande én de feedback, ook van provincies (https://github.com/bimloket/contractspecificaties/issues/48), op de geformuleerde eistypen. Er is gewoon geen nen-norm die daar duidelijk over is.

**Comment by ElisabethKloren** [comment]
> Bij het Provinciaal Contractenbuffet en ProContract schreven we in september 2021 al het volgende:
> 
> [eisenindeling.pdf](https://github.com/Stichting-CROW/PCB/files/10344379/eisenindeling.pdf)

We zullen moeten kijken hoe we deze eisindeling kunnen relateren aan de data-uitwisseltabellen; deze link leidt duidelijk naar een "voor mensen leesbare samenvatting van de eis" dat is gewoon wat anders dan het "tabeluitwisselformaat"

**Comment by RiX012** [comment]
Klopt, volgens mij zou PCB zelf een consensus moeten vinden en deze zelf onderhouden als LinkedData set(je).

**Comment by BobNonnekens** [comment]
Goed, dan werken we met een conversietabelletje. Ik maak een concept en leg deze ter controle bij jullie (@RiX012 & @ElisabethKloren ) voor. Hiermee is dit issue gereed.
