### ISSUE TITLE
Data onder link CROW Basisspecificaties niet zichtbaar in chrome of edge

### ISSUE THREAD

**Issue by MauMuij** [Stichting-CROW/PCB#41]
**Betreft onderdeel**:  De data onder de link CROW Basisspecificaties (https://www.crow.nl/provinciaal-contractenbuffet/provinciaal-contractenbuffet/pcb-contract-opstellen#Hoe_kan_ik_de_contractdata_benaderen?_) is niet zichtbaar in zowel Chrome als Edge. De boom is wel zichtbaar maar de onderliggende data niet.
Dit geld ook voor de data onder de link van Eisenset Provincie Utrecht (https://publicatiesonline.crow.nl/Menu/GetSemmPublications?applicationId=3&viewId=2)
**Verbetervoorstel**: laagste niveau in de data zichtbaar maken.
**Beoogd doel van de verbetering**: Überhaupt gebruik kunnen maken van de data!

**Comment by BobNonnekens** [comment]
Dag Maurice,

dank voor het attenderen.
Ik heb dit natuurlijk zelf ook even getest en loop nu tegen hetzelfde probleem aan (was ten tijde van het publiceren niet zo).
Ik speel deze vraag door aan de IT-collega's.
Als de oorzaak helder is laat ik dit weten en als het opgelost is ook. Ik kan nu echter geen termijn voorspellen waarop dit gereed is.
Als je op dit moment specifieke data nodig hebt, wil je mij dat even mailen? Dan probeer ik je daaraan langs andere weg te helpen.

**Comment by BobNonnekens** [comment]
@RiX012 Weet jij raad, Rik? Ook intern CROW komen geen functies, objecten of activiteiten in beeld onder Chrome of Edge.

**Comment by RiX012** [comment]
Ik kan het alleen reproduceren voor de PCB sets (behalve Openbare Verlichting). De rest lijkt het gewoon te doen. Ik ga het even na.

**Comment by RiX012** [comment]
Voor mij werken nu alle sets weer. Hopelijk is hiermee het issue opgelost. @BobNonnekens check jij dit even.
