### ISSUE TITLE
Link onder PCB naar LDP werkt niet

### ISSUE THREAD

**Issue by MauMuij** [Stichting-CROW/PCB#42]
**Betreft onderdeel**:  Onderaan de pagina Tools en documenten (https://www.crow.nl/provinciaal-contractenbuffet/provinciaal-contractenbuffet/tools-en-documenten) werk de link naar het ldp (https://www.crow.nl/thema-s/informatiemanagement/linked-data-platform-(1)) niet.
**Verbetervoorstel**: opnieuw linken
**Beoogd doel van de verbetering**: inzicht in LDP

**Comment by BobNonnekens** [comment]
Dag Maurice,

dank voor het attenderen. 
Deze link gaan we herstellen op kortst mogelijke termijn. Zodra dat gepiept is laten we dat hier weten.

Maar daar ben jij op dit moment nog niet mee geholpen. Zijn er specifieke zaken die je in het LDP wil opzoeken? Stuur mij even een mailtje, dan help ik je daarmee.
Wist je trouwens dat onze club van digitale innovatie een mooie standaard heeft opgesteld over versiebeheer van data ín de datasets (je kunt wel hele datasets onderwerpen aan versiebeheer, maar dit kan op op onderdeelniveau). Mooi leesvoer dat je [in de huidige ontwikkelversie hier kunt vinden](url=https://docs.crow.nl/wp/ldversiebeheer/); doe er je voordeel mee!

**Comment by BobNonnekens** [comment]
Opgelost met nieuwe website
