### ISSUE TITLE
voorbeelddocument VSP (20220217) is ouder dan eisenset VSP (20220713) 

### ISSUE THREAD

**Issue by MauMuij** [Stichting-CROW/PCB#46]
**Betreft onderdeel**:  voorbeelddocument VSP (20220217) is ouder dan eisenset VSP (20220713) en staan beiden op de te downloaden documentenlijst. (https://www.crow.nl/provinciaal-contractenbuffet/provinciaal-contractenbuffet/tools-en-documenten) Dit kan tot verwarring . fouten leiden. 
**Verbetervoorstel**: Voorstel voorbeelddocument verwijderen
**Beoogd doel van de verbetering**: voorkomen gebruik maken van oudere versies.

**Comment by BobNonnekens** [comment]
Dag Maurice,
je hebt helaas gelijk. Uit de Inleiding bij de eisenset blijkt dit ook bij het onderdeel 0.5 Revisies:.

_**0.5	Revisies**	
	**Versie 1.0**	Niet vastgesteld wegens introductie Wet BRO
	**Versie 2.0**	Vastgesteld en vrijgegeven door Kernteam PCB 2020-03-19
	**versie 2.1**	Omzetting vanuit ProContract Word-document door Bob Nonnekens (CROW) op verzoek Thomas Munster (Prov. Noord-Holland).
		Vastgesteld dat in de eisnummering versie 2.0 fouten zijn geslopen. Een heel aantal eisen hebben dezelfde nummering gekregen waardoor verwarring ontstaat en geautomatiseerde verwerking tot vastlopende processen leidt.
		In **versie 2.1** is in kolom C de eisnummering volgens het vastgestelde product te zien. In oranje-geel zijn de dubbele (extra) eisnummers gemarkeerd. In kolom D (lichtgroen) is het voorstel opgenomen om de ontdubbeling door te voeren. Effectief komt het er op neer dat vanaf het bestaande hoogste eisnummer verder genummerd wordt.
		Er zijn weliswaar vrijgevallen eisnummers omdat  deze eisen niet in het uiteindelijke product zijn overgenomen (gemarkeerd met ‘VERVALLEN’) maar het gebruik van deze nummers levert teveel versnippering op en maakt het traceren van het ontstaan van eisen onmogelijk. Dat laatste geldt ook als  de nummering helemaal opnieuw zouden gesorteerd wordt comform de opbouw van het document. Vandaar het toepassen van nieuwe eisnummers.
	**versie 3.0**	Op het omnummervoorstel als opgenomen in versie 2.1 is geen commentaar gekomen, waarop de omnummering is doorgevoerd. Deze versie is vastgesteld als versie 3.0 d.d. 2020-07-03_

Momenteel loopt een actualisatie van de eisen uit dit procesdeel. Het voorstel dat momenteel behandeld wordt is dat ná vaststelling van deze actualisatie er budget en capaciteit moet worden gereserveerd om deze eisenset te verwerken in een nieuwe versie van het voorbeelddocument en dan de versienummering gelijk te laten lopen.
